
export const GET_PAYMENT_BEGIN = 'GET_PAYMENT_BEGIN'
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS'
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL'

export const GET_CHECKOUT_BEGIN = 'GET_CHECKOUT_BEGIN'
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS'
export const GET_CHECKOUT_FAIL = 'GET_CHECKOUT_FAIL'